FROM quay.io/vektorcloud/base:latest

RUN apk --no-cache add docker

COPY mesos-tiny/ /
COPY entrypoint.sh /

ENV MESOS_WORK_DIR /tmp/mesos
ENV MESOS_CONTAINERIZERS docker,mesos
# https://mesosphere.github.io/marathon/docs/native-docker.html
ENV MESOS_EXECUTOR_REGISTRATION_TIMEOUT 5mins
# https://issues.apache.org/jira/browse/MESOS-3793
ENV MESOS_LAUNCHER posix

VOLUME /tmp/mesos

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/usr/sbin/mesos-slave"]
